# -*- coding: utf-8 -*-
"""
Módulo contendo o histórico de alterações (changelogs) dos sistemas NBS e Linx/Apollo.
Importado em ui_nbs.py e ui_apollo.py para renderização nas abas 'Sobre'.
"""

CHANGELOG_NBS = (
    "=== Versão 1.3.0 ===\n"
    "- Ajustados os layouts das abas para se manterem estáticos com dimensionamento rígido de botões e contêineres, evitando deslocamentos ao atualizar as caixas de log.\n"
    "- Adicionada captura automática de tela (print da tela final salvo em .png na pasta 'screenshots/') ao concluir a execução do script de banco NBS e validador.\n"
    "- Refatorado o utilitário de Reinício Remoto nos Utilitários: higienização automática de IPs (removendo caminhos UNC como \\\\IP\\c$\\NBS), suporte ao gerenciamento de lista de IPs salvos e monitoramento em tempo real do ciclo de reinício via PING (com badges visuais ONLINE/OFFLINE).\n\n"
    "=== Versão 1.2.9 ===\n"
    "- Adicionado painel de monitoramento e controle (iniciar/parar) do serviço do Payara (nome padrão 'domain1') na aba de Atualização CRMWeb, permitindo configurar nomes de serviço customizados.\n\n"
    "=== Versão 1.2.8  ===\n"
    "- Adicionado o novo menu 'Atualização CRMWeb' no painel do sistema NBS.\n"
    "- Implementada a execução elevada como administrador (UAC) de utilitários CRMWeb (WEUpdate.exe e JManagerClient.exe) com passagem dinâmica de parâmetros de linha de comando.\n"
    "- Criada interface de cards dedicada com log detalhado e mocks para simulação em ambiente Linux.\n\n"
    "=== Versão 1.2.7  ===\n"
    "- Ajustado o Utilitário de Limpeza da pasta NBS para suportar seleção dinâmica de pastas, buscas por Glob/Regex e controle de filtragem (limitado a arquivos .exe).\n"
    "- Adicionada a nova ferramenta de Limpeza por Extensão na aba NBS para permitir a busca e exclusão segura de tipos de arquivos customizados (.log, .tmp, .zip, etc.).\n\n"
    "=== Versão 1.2.6  ===\n"
    "- Implementada criptografia simétrica (XOR + Base64) nas configurações locais, ocultando credenciais de banco e FTP contra visualização em plain-text.\n"
    "- Redirecionado o armazenamento das configurações para as pastas padrão do usuário (%APPDATA% no Windows e ~/.config no Linux) com o nome 'config.enc'.\n"
    "- Criado fluxo de migração automática e exclusão segura do arquivo 'config.json' legado.\n"
    "- Corrigido flickering/redimensionamento no grid de credenciais de banco de dados na aba de Scripts.\n\n"
    "=== Versão 1.2.5  ===\n"
    "- Corrigida globalmente a cor do texto dos botões, menus de opções e botões segmentados no modo claro.\n"
    "- A correção foi aplicada diretamente no dicionário global de temas (ThemeManager.theme), evitando código hardcoded nos widgets.\n\n"
    "=== Versão 1.2.4  ===\n"
    "- Ativado o callback de log do processo de distribuição de arquivos (Cópia para servidores).\n"
    "- Adicionado um Console de Log (textbox) em tempo real na tela de Distribuição.\n"
    "- Implementada geração automática do arquivo 'distribuicao.log' na pasta de atualização do dia para auditoria de erros e renomeações.\n\n"
    "=== Versão 1.2.3  ===\n"
    "- Adicionada validação do backup local para evitar cópias e compactações desnecessárias caso o backup da pasta local do NBS já exista e esteja atualizado.\n\n"
    "=== Versão 1.2.2  ===\n"
    "- Adicionada validação de arquivos já baixados localmente para pular a transferência de arquivos idênticos.\n"
    "- Implementada comparação por hash MD5 do servidor (se suportado via comandos FTP MD5/XMD5) e fallback por tamanho de arquivo.\n\n"
    "=== Versão 1.2.1  ===\n"
    "- Adicionado travamento de todos os inputs, checkboxes e botão 'Recalcular' da aba de download durante a execução (incluindo em pausa).\n"
    "- Configurado o desbloqueio automático dos inputs da aba de download apenas ao finalizar ou cancelar o processo.\n\n"
    "=== Versão 1.2.0  ===\n"
    "- Corrigido bug NameError 'shutil' is not defined ao deletar a pasta original de backup no Windows/Linux.\n\n"
    "=== Versão 1.1.9  ===\n"
    "- Adicionada nova aba de 'Utilitários' na barra lateral.\n"
    "- Desenvolvida ferramenta de 'Limpeza de Executáveis da Pasta NBS' local.\n"
    "- Implementado pop-up modal para listagem de arquivos (.exe) com seleção por checkbox.\n"
    "- Adicionada caixa de confirmação dupla com listagem dos executáveis marcados antes da exclusão física.\n\n"
    "=== Versão 1.1.8  ===\n"
    "- Movido o controle de Aparência (Tema) da barra lateral para a tela de Configurações.\n"
    "- Definida a inicialização padrão do sistema no modo Escuro (Dark).\n"
    "- Modificado o comportamento do tema para aplicar as alterações apenas após salvar as configurações.\n\n"
    "=== Versão 1.1.7  ===\n"
    "- Adicionados controles de 'Pausar' / 'Retomar' e 'Cancelar' para o fluxo de download.\n"
    "- Adicionado travamento de navegação lateral durante a execução do download para evitar inconsistências e congelamentos.\n"
    "- Implementado descarte automático de arquivos parciais corrompidos quando o download é cancelado.\n\n"
    "=== Versão 1.1.6  ===\n"
    "- Adicionada flag na tela de download para compactar a pasta de backup (.zip) com compressão máxima (nível 9).\n"
    "- Adicionada flag para excluir a pasta original de backup após a compactação ser concluída com sucesso.\n\n"
    "=== Versão 1.1.5  ===\n"
    "- Implementado tratamento de arquivos bloqueados/em uso no destino durante cópia (renomeação automática com timestamp milissegundos).\n\n"
    "=== Versão 1.1.4  ===\n"
    "- Ajustado o destino das marcas/interfaces para a raiz da pasta 'Modulos' (removendo subpastas 'interfaces/').\n"
    "- Ajustado o monitoramento de scripts: monitora se o executável principal inicia automaticamente o 'NBSScriptsRun.exe'.\n"
    "- Implementada espera automática de término do validador se detectado em execução, com fallback manual caso contrário.\n\n"
    "=== Versão 1.1.3  ===\n"
    "- Atualizado fluxo de execução do banco: agora executa o script principal e, ao término, executa o validador 'NBSScriptsRun.exe'.\n"
    "- Implementada verificação de existência e término síncrono para ambos os processos antes de reportar a conclusão.\n\n"
    "=== Versão 1.1.2  ===\n"
    "- Criada aba de 'Configurações' dedicada para edição e gravação manual dos parâmetros do config.json.\n"
    "- Simplificada a aba de 'Download & Backup' com a remoção de inputs estáticos e adição de painel informativo de caminhos ativos.\n"
    "- Adicionados campos de edição gráfica para os parâmetros de banco de dados (User, Pass, Schema, Service Name).\n\n"
    "=== Versão 1.1.1  ===\n"
    "- Adicionada a chave 'db_name' (Service Name do banco) nas configurações (config.json) e na interface.\n"
    "- Ajustada a geração de 'site.xml': agora preenche <db_name> com o Service Name e <host> com o Schema/Host.\n"
    "- Atualizados os campos id_site e descricao no arquivo 'site.xml' para fixar o valor 'NBS'.\n\n"
    "=== Versão 1.1.0  ===\n"
    "- Redesenho completo do Layout: Substituído o menu superior por navegação vertical na barra lateral esquerda.\n"
    "- Adicionada a aba 'Sobre o App' integrada para exibição de versão, contatos e histórico de alterações.\n"
    "- Implementado download compulsório da pasta de interfaces/especificas do FTP (respeitando a data de corte).\n\n"
    "=== Versão 1.0.0  ===\n"
    "- Backup automatizado dos executáveis locais (.exe) antes de realizar downloads.\n"
    "- Conexão FTP inteligente para verificação de data de modificação de arquivos (comando MDTM).\n"
    "- Cálculo automático da data da última atualização a partir do histórico de diretórios.\n"
    "- Execução elevada (UAC como Administrador) do script do banco com espera síncrona de término (UAC via ctypes).\n"
    "- Adicionado controle portátil de múltiplos servidores para distribuição de rede.\n"
    "- Download interativo de marcas com filtro de pesquisa e seleção múltipla.\n"
    "- Download do instalador NFE e script de transição de ano.\n"
    "- Adicionada flag de Instalação Inicial que baixa todas as DLLs e ignora a data de corte.\n"
    "- Detecção automática do S.O. com emulação (mocks) no Linux para testes locais do fluxo."
)

CHANGELOG_APOLLO = (
    "=== Versão 1.1.1 ===\n"
    "- Ajustados os layouts das abas do sistema Apollo para se manterem estáticos com dimensões fixas de botões e caixas de log.\n"
    "- Adicionado novo atalho na aba Utilitários para abrir o Agendador de Tarefas do Windows (taskschd.msc).\n"
    "- Atualizado o utilitário de reinício remoto com sanitização de IP, gerenciamento de lista de servidores salvos e monitoramento de status via PING.\n\n"
    "=== Versão 1.1.0 ===\n"
    "- Adicionada opção de backup dos executáveis (.exe) e bibliotecas (.dll) da pasta C:\\Apollo\\atualiza antes da descompactação.\n"
    "- Adicionada flag na seleção de pacotes para ativar/desativar o backup do Apollo.\n"
    "- A pasta de backup do Apollo agora é gerada dinamicamente contendo a data no nome (ex: backup_DDMMYYYY).\n"
    "- Adicionada opção no menu de Serviços do Windows para encerrar processos do ApolloServer (powershell stop-process -name *serverapp*).\n"
    "- Suporte ao encerramento de processos executáveis ativos (como wsContabil.exe) por padrão Regex ou nome via PowerShell.\n"
    "- Limpeza e exclusão automática dos arquivos zipados (.zip) da pasta C:\\atualizacao após a descompactação e cópia dos arquivos.\n\n"
    "=== Versão 1.0.9 ===\n"
    "- Corrigido problema de detecção de status de serviços do Windows (DFeServico, etc.) em sistemas operacionais em outros idiomas (como Português-BR) adaptando a leitura para múltiplos padrões de resposta do comando 'sc query'.\n\n"
    "=== Versão 1.0.8 ===\n"
    "- Adicionado o novo Utilitário de Limpeza por Extensão na aba Linx, permitindo a pesquisa e remoção de arquivos de qualquer extensão customizada (.log, .tmp, .zip, etc.).\n\n"
    "=== Versão 1.0.7 ===\n"
    "- Adicionada opção para download do Linx DMS Integrador (arquivo LinxDMSIntegrador.zip) e monitoramento do serviço dmLDIServer.\n"
    "- Ajustadas pastas padrão do utilitário de exclusão Linx para C:\\Apollo e C:\\3camadas, e adicionado botão de busca para pasta customizada.\n"
    "- Implementada criptografia simétrica (XOR + Base64) das configurações locais gravadas em Appdata/Roaming ou ~/.config/AtualizadorSistemas/config.enc.\n"
    "- Integrada descompactação e execução elevada como Administrador para arquivos .exe e .msi internos do Integrador.\n\n"
    "=== Versão 1.0.6 ===\n"
    "- Adicionada aba 'Utilitários Linx' com exclusão de arquivos executáveis (.exe) e bibliotecas (.dll).\n"
    "- Suporte a filtros de pesquisa inteligentes com padrões Glob (ex: *2026*.dll) e Expressões Regulares (Regex).\n"
    "- Criado painel de monitoramento e controle assíncrono para os Serviços do Windows (DFeServico, RedirecionaDatasnap, VerificaServer3Camadas).\n"
    "- Implementado fluxo automatizado de descompactação e movimentação de arquivos nos diretórios corretos (Apollo/Atualiza, 3Camadas Server/Client).\n"
    "- Suporte para execução do Instalador Web (.exe/.msi) com privilégios de Administrador.\n"
    "- Corrigidos problemas de segurança de threads (TclError) ao atualizar status de serviços de forma assíncrona.\n"
    "- Ajustado tamanho e alinhamento dos cards na tela inicial (350px de largura com ancoragem de textos à esquerda).\n\n"
    "=== Versão 1.0.5 ===\n"
    "- Configuração de valores padrão para versão (5.19) e caminhos de atualização (C:\\atualizacao no Windows e /home/robson.santos@DTACENTER.MR/Dev/AtualizadorNBS no Linux).\n"
    "- Salvamento automático de versão e caminho ao perder o foco (FocusOut), pressionar Enter (Return) ou ao fechar o programa.\n"
    "- Corrigido problema de carregamento de interface que sobrescrevia as configurações com campos vazios na inicialização.\n"
    "- Implementação de aba dedicada 'Sobre o Linx' com changelog e documentação específica.\n\n"
    "=== Versão 1.0.4 ===\n"
    "- Criação da aba de Configurações Linx para customização dinâmica de todos os templates de URL (HTTP).\n"
    "- Correção de layout e compatibilização de temas (Light/Dark) na interface Linx.\n\n"
    "=== Versão 1.0.3 ===\n"
    "- Integração do controle de pausa ('Pausar' / 'Retomar') e cancelamento do download de pacotes Linx.\n"
    "- Bloqueio completo de campos e botões da aba Linx durante o andamento do processo de download.\n\n"
    "=== Versão 1.0.2 ===\n"
    "- Adicionado suporte para múltiplos tipos de pacotes/marcas Linx: LINXDMS, HPE, BRAVOS, TOYOTA.\n"
    "- Correção na formatação da versão, adicionando o prefixo 'v' automaticamente quando ausente.\n\n"
    "=== Versão 1.0.1 ===\n"
    "- Adicionado suporte a pacotes de 3 Camadas (Server / Client) e instalador Web completo.\n"
    "- Implementação de progresso visual (barra de progresso) e console de log em tempo real para downloads HTTP.\n\n"
    "=== Versão 1.0.0 ===\n"
    "- Implementação inicial da aba de Downloads do Linx DMS.\n"
    "- Suporte para download do pacote Delphi (Padrão) via HTTP.\n"
    "- Seleção de múltiplos pacotes adicionais: DMS Comissões, Apoio (Troca Fornecedor, Troca Série, Verifica Diária).\n"
    "- Preenchimento inteligente de URLs com substituição dinâmica de versão e tipo de pacote."
)
